### ISSUE TITLE
Biztalk pipeline component project not available under Biztalk projects in visual studio 2013 for Biztalk 2013 R2

### ISSUE THREAD

**Issue by DhivakarAva** [DanieleCervi/BiztalkCustomPipelineComponent#1]
Please find my issue in below link:
[https://social.msdn.microsoft.com/Forums/en-US/6f45d49c-cecf-4d87-be03-4bb26737d8f8/biztalk-pipeline-component-project-not-available-under-biztalk-projects-in-visual-studio-2013-for?forum=biztalkgeneral&prof=required](url)

Kindly provide me a solution to Install pipeline component wizard in visual studio 2013.

**Comment by DanieleCervi** [comment]
Hello, i just released a new version that should fix the version issue. Let me know!
